spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: phoenix-config-dev
---
spring:
  profiles: test #测试环境
  application:
    name: phoenix-config-test
---
spring:
  profiles: pex #pex
  application:
    name: phoenix-config-pex
